version: '3.8'

services:
  phosphor:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./backend/uploads:/app/backend/uploads
      - ./backend/data:/app/backend/data
      - ./backend/src:/app/backend/src
      - ./frontend/src:/app/frontend/src
    restart: unless-stopped
    environment:
      - NODE_ENV=development
